import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "ja" | "en";

const STORAGE_KEY = "timetable_language";

const translations = {
  ja: {
    "app.title": "時間割管理",
    "app.subtitle": "Timetable Manager",
    "common.loading": "読み込み中...",
    "common.save": "保存",
    "common.saved": "保存済み",
    "common.unsaved": "未保存",
    "common.done": "完了",
    "common.error": "エラー",
    "common.cancel": "解除",
    "common.settings": "設定",
    "common.language": "言語",
    "common.japanese": "日本語",
    "common.english": "English",
    "common.justNow": "たった今",
    "common.minutesAgo": "分前",
    "sidebar.newFile": "新規作成",
    "sidebar.openFile": "ファイルを開く",
    "sidebar.saveWithUnsaved": "保存（未保存あり）",
    "sidebar.loadSample": "サンプルデータを読み込む",
    "sidebar.homeroom": "担任",
    "sidebar.notSet": "未設定",
    "sidebar.multiSubject": "複数教科",
    "sidebar.nav.grid": "週間時間割",
    "sidebar.nav.stats": "クラス別集計",
    "sidebar.nav.teachingPlan": "指導計画",
    "sidebar.nav.history": "変更履歴",
    "sidebar.nav.audit": "適用ログ",
    "sidebar.weekNav": "週の移動",
    "sidebar.thisWeek": "今週",
    "sidebar.jumpByDate": "日付で移動",
    "sidebar.pickDate": "移動先の日付を選択",
    "sidebar.undo": "元に戻す",
    "sidebar.export": "エクスポート",
    "sidebar.googleCalendar": "Googleカレンダー連携",
    "sidebar.semesterSettings": "学期設定を変更",
    "sidebar.holidaySettings": "祝日・休校日の設定",
    "sidebar.subjectManagement": "教科の管理",
    "sidebar.mobileMenuStyle": "モバイルメニュー形式",
    "sidebar.mobileBottomSheet": "下から開く",
    "sidebar.mobileSlideLeft": "左から開く",
    "drive.restoring": "ログイン状態を復元中...",
    "drive.loginExpired": "Googleログインが切れました。再ログインしてください。",
    "drive.relogin": "再ログイン",
    "drive.requestCookie": "Cookie許可を要求",
    "drive.requestCookieTitle": "サードパーティCookieの許可をブラウザに要求します",
    "drive.login": "Googleでログイン",
    "drive.syncing": "同期中...",
    "drive.syncedSuffix": " に同期",
    "drive.synced": "同期済み",
    "drive.syncError": "同期エラー",
    "drive.connected": "Drive連携中",
    "drive.disconnect": "解除",
    "drive.reauthTitle": "アカウントの権限を再確認します",
    "drive.logoutTitle": "ログアウト",
    "drive.autoSyncHelp": "✓ 保存のたび自動で同期（隠しフォルダ）",
    "drive.syncOnly": "Drive同期のみ",
    "drive.syncOnlyTitle": "ローカル保存なしで Drive の隠しフォルダだけ更新します",
    "drive.restore": "Driveから復元",
    "drive.backupTitle": "マイドライブ/時間割管理/ に日付付きバックアップを作成",
    "drive.backupToMyDrive": "マイドライブにバックアップ",
    "drive.backupDoneSuffix": " にバックアップ完了",
    "drive.backupFailed": "バックアップ失敗",
    "drive.backupDestination": "→ マイドライブ / 時間割管理 / に保存",
    "drive.backupList": "バックアップ一覧・復元",
    "toast.loaded": "読み込み完了",
    "toast.zipLoaded": "ZIPから読み込み完了",
    "toast.supportedFiles": "対応ファイル: .timetable または .zip",
    "toast.loadError": "読み込みエラー",
    "toast.saved": "保存しました",
    "toast.driveSaved": "Google Driveに保存しました",
    "toast.driveSaveFailed": "Drive保存に失敗しました",
    "toast.backupFailed": "バックアップに失敗しました",
    "toast.driveEmpty": "Google Driveにデータがありませんでした",
    "toast.driveLoaded": "Google Driveから読み込みました",
    "toast.driveLoadFailed": "Drive読み込みに失敗しました",
    "home.titleFallback": "時間割管理",
    "home.saveLocalTitle": "クリックしてローカル保存",
    "home.import": "インポート",
    "home.importTitle": "パッチインポート",
    "home.export": "エクスポート",
    "home.exportTitle": "エクスポート（Excel / PDF / ICS / Google連携 / 生データ）",
    "home.googleLink": "Google連携",
    "home.googleLinkTitle": "Googleカレンダーに直接追加",
    "home.print": "印刷",
    "home.moreActions": "その他の操作",
    "home.exportMenu": "エクスポート",
    "home.exportMenuItem": "エクスポート...",
    "home.googleCalendarMenuItem": "Googleカレンダー連携...",
    "home.rawCsv": "生データ（CSV）",
    "home.patchImport": "パッチインポート",
    "home.printPreview": "印刷プレビュー",
    "weekGrid.noDataTitle": "データを読み込んでください",
    "weekGrid.noDataLine1": "左のサイドバーから「ファイルを開く」または",
    "weekGrid.noDataLine2": "「新規作成」でデータを準備できます",
    "weekGrid.firstTerm": "前期",
    "weekGrid.secondTerm": "後期",
    "weekGrid.termSuffix": "学期",
    "weekGrid.academicYearSuffix": "年度",
    "weekGrid.weekPatternTitle": "この週のパターンを変更",
    "weekGrid.weekPatternChangeTitle": "タップして週パターンを変更",
    "weekGrid.weekA": "A週",
    "weekGrid.weekB": "B週",
    "weekGrid.weekC": "C週",
    "weekGrid.weekD": "D週",
    "weekGrid.resetAuto": "自動計算に戻す",
    "weekGrid.homeroom": "担任",
    "weekGrid.backToThisWeek": "今週に戻る",
    "weekGrid.jumpByDate": "日付で移動",
    "weekGrid.pickDate": "移動先の日付を選択",
    "weekGrid.multiSelectActive": "複数選択中",
    "weekGrid.multiSelect": "複数選択",
    "weekGrid.exitMultiSelect": "複数選択モードを解除",
    "weekGrid.enterMultiSelect": "複数のコマを同時編集するモードに入る",
    "weekGrid.subjectView": "教科ビュー",
    "weekGrid.classView": "クラスビュー",
    "weekGrid.subjectViewTip": "教科を大きく、クラスを小さく表示中。クリックで切り替え",
    "weekGrid.classViewTip": "クラスを大きく、教科を小さく表示中。クリックで切り替え",
    "weekGrid.filterByClass": "クラスで絞り込み",
    "weekGrid.classFilter": "クラスフィルター",
    "weekGrid.filterBySubject": "教科で絞り込み",
    "weekGrid.subjectFilter": "教科フィルター",
    "weekGrid.showAll": "すべて表示",
    "weekGrid.periodTimes": "時程表",
    "weekGrid.periodTimesSetTip": "時程表設定済（クリックで編集）",
    "weekGrid.periodTimesTip": "各コマの開始・終了時刻を設定（ICS書き出し用）",
    "weekGrid.llmImport": "AI(LLM)読み取り",
    "weekGrid.readFromImage": "画像から読み取る",
    "weekGrid.timetable": "時間割",
    "weekGrid.periodTimesShort": "時程表",
    "weekGrid.annualSchedule": "年間予定表",
    "weekGrid.saturdayClass": "土曜授業",
    "weekGrid.saturdayClassTip": "この週のみ土曜日を授業日として表示",
    "weekGrid.sundayClass": "日曜授業",
    "weekGrid.sundayClassTip": "この週のみ日曜日を授業日として表示",
    "weekGrid.multiSelectMode": "複数選択モード",
    "weekGrid.multiSelectHelp": "セルをタップで選択、Shift+クリックで範囲選択、Cmd/Ctrl+クリックで追加選択",
    "weekGrid.selectedSlotsSuffix": "コマ選択中",
    "weekGrid.release": "解除",
    "weekGrid.previousWeek": "前の週",
    "weekGrid.nextWeek": "次の週",
    "weekGrid.noData": "データなし",
    "weekGrid.schoolClosed": "休校",
    "weekGrid.periodSuffix": "限",
    "weekGrid.empty": "空き",
    "weekGrid.legend": "凡例:",
    "weekGrid.gradeSuffix": "年",
    "weekGrid.dragSwap": "ドラッグ＆ドロップで交換",
    "weekGrid.longPressSwap": "長押しでドラッグ交換",
    "weekGrid.swap": "交換",
    "weekGrid.todaySchedule": "本日の授業予定",
    "weekGrid.noTodayClasses": "本日の授業はありません",
    "autoRestore.title": "前回の作業を復元しますか？",
    "autoRestore.description": "前回の編集内容が自動保存されています。",
    "autoRestore.fileName": "ファイル名",
    "autoRestore.lastSaved": "最終保存",
    "autoRestore.discard": "破棄して新規",
    "autoRestore.restore": "復元する",
    "confirmChange.title": "変更の確認",
    "confirmChange.warning": "警告",
    "confirmChange.cancel": "キャンセル",
    "confirmChange.run": "実行",
    "confirmChange.runWithWarnings": "警告を無視して実行",
    "confirmChange.empty": "空き",
    "confirmChange.delete": "削除",
    "confirmChange.add": "追加",
    "confirmChange.move": "移動",
    "confirmChange.swap": "交換",
    "semester.add": "学期を追加",
    "semester.semester": "学期",
    "semester.startDate": "始業日",
    "semester.endDate": "終業日",
    "semester.copyNotice": "基本時間割・クラス設定は現在の学期から引き継がれます。",
    "semester.cancel": "キャンセル",
    "semester.addButton": "追加",
    "semester.deleteTitle": "この学期を削除",
    "semester.monthSuffix": "月",
    "stats.emptyStats": "ファイルを読み込むと集計が表示されます",
    "stats.semesterStats": "学期別集計",
    "stats.annualStats": "年間集計",
    "stats.classStats": "クラス別集計",
    "stats.subjectStats": "教科別集計",
    "stats.asOfDate": "集計基準日",
    "stats.backToToday": "今日に戻す",
    "stats.asOfHelp": "※ この日付以前を「実施済み」として集計します",
    "stats.totalPeriods": "総コマ数",
    "stats.annualTotalPeriods": "年間総コマ数",
    "stats.completed": "実施済み",
    "stats.remaining": "残り",
    "stats.periodUnit": "コマ",
    "stats.semesterTotalSuffix": "学期合計",
    "stats.termLowerSingular": "学期",
    "stats.termLowerPlural": "学期",
    "stats.class": "クラス",
    "stats.total": "合計",
    "stats.totalShort": "計",
    "stats.doneShort": "済",
    "stats.remainingShort": "残",
    "stats.progress": "進捗",
    "stats.noMultiSemester": "複数学期のデータがありません",
    "stats.noSubjectData": "教科情報のあるコマがありません",
    "stats.subjectDataHint": "授業変更パネルからコマに教科を設定すると集計されます",
    "history.emptyLoad": "ファイルを読み込むと変更履歴が表示されます",
    "history.noneTitle": "変更履歴はまだありません",
    "history.noneDescription": "授業変更を行うと、ここに履歴が表示されます",
    "history.title": "変更履歴",
    "history.undo": "元に戻す",
    "history.operationCountSuffix": "件の操作",
    "audit.emptyLoad": "ファイルを読み込むと適用ログが表示されます",
    "audit.title": "適用ログ",
    "audit.warning": "警告",
    "audit.error": "エラー",
    "audit.none": "ログはありません",
    "audit.periodSuffix": "限",
  },
  en: {
    "app.title": "Timetable Manager",
    "app.subtitle": "Timetable Manager",
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.saved": "Saved",
    "common.unsaved": "Unsaved",
    "common.done": "Done",
    "common.error": "Error",
    "common.cancel": "Disconnect",
    "common.settings": "Settings",
    "common.language": "Language",
    "common.japanese": "Japanese",
    "common.english": "English",
    "common.justNow": "Just now",
    "common.minutesAgo": "min ago",
    "sidebar.newFile": "New File",
    "sidebar.openFile": "Open File",
    "sidebar.saveWithUnsaved": "Save (unsaved changes)",
    "sidebar.loadSample": "Load sample data",
    "sidebar.homeroom": "Homeroom",
    "sidebar.notSet": "Not set",
    "sidebar.multiSubject": "Multiple subjects",
    "sidebar.nav.grid": "Weekly Timetable",
    "sidebar.nav.stats": "Class Stats",
    "sidebar.nav.teachingPlan": "Teaching Plan",
    "sidebar.nav.history": "Change History",
    "sidebar.nav.audit": "Apply Log",
    "sidebar.weekNav": "Week Navigation",
    "sidebar.thisWeek": "This Week",
    "sidebar.jumpByDate": "Jump by Date",
    "sidebar.pickDate": "Select a date",
    "sidebar.undo": "Undo",
    "sidebar.export": "Export",
    "sidebar.googleCalendar": "Google Calendar",
    "sidebar.semesterSettings": "Semester Settings",
    "sidebar.holidaySettings": "Holidays / School Closures",
    "sidebar.subjectManagement": "Manage Subjects",
    "sidebar.mobileMenuStyle": "Mobile Menu Style",
    "sidebar.mobileBottomSheet": "Bottom Sheet",
    "sidebar.mobileSlideLeft": "Slide from Left",
    "drive.restoring": "Restoring login...",
    "drive.loginExpired": "Google login expired. Please sign in again.",
    "drive.relogin": "Sign in again",
    "drive.requestCookie": "Request cookie access",
    "drive.requestCookieTitle": "Request browser permission for third-party cookie access",
    "drive.login": "Sign in with Google",
    "drive.syncing": "Syncing...",
    "drive.syncedSuffix": " synced",
    "drive.synced": "Synced",
    "drive.syncError": "Sync error",
    "drive.connected": "Drive connected",
    "drive.disconnect": "Disconnect",
    "drive.reauthTitle": "Reconfirm account permissions",
    "drive.logoutTitle": "Sign out",
    "drive.autoSyncHelp": "Auto-sync on every save (hidden folder)",
    "drive.syncOnly": "Sync to Drive only",
    "drive.syncOnlyTitle": "Update only the hidden Drive copy without local save",
    "drive.restore": "Restore from Drive",
    "drive.backupTitle": "Create a dated backup in My Drive/Timetable Manager/",
    "drive.backupToMyDrive": "Back up to My Drive",
    "drive.backupDoneSuffix": " backup complete",
    "drive.backupFailed": "Backup failed",
    "drive.backupDestination": "Saved to My Drive / Timetable Manager /",
    "drive.backupList": "Backup List / Restore",
    "toast.loaded": "Loaded",
    "toast.zipLoaded": "Loaded from ZIP",
    "toast.supportedFiles": "Supported files: .timetable or .zip",
    "toast.loadError": "Load error",
    "toast.saved": "Saved",
    "toast.driveSaved": "Saved to Google Drive",
    "toast.driveSaveFailed": "Failed to save to Drive",
    "toast.backupFailed": "Backup failed",
    "toast.driveEmpty": "No data found in Google Drive",
    "toast.driveLoaded": "Loaded from Google Drive",
    "toast.driveLoadFailed": "Failed to load from Drive",
    "home.titleFallback": "Timetable Manager",
    "home.saveLocalTitle": "Click to save locally",
    "home.import": "Import",
    "home.importTitle": "Patch import",
    "home.export": "Export",
    "home.exportTitle": "Export (Excel / PDF / ICS / Google / Raw data)",
    "home.googleLink": "Google",
    "home.googleLinkTitle": "Add directly to Google Calendar",
    "home.print": "Print",
    "home.moreActions": "More actions",
    "home.exportMenu": "Export",
    "home.exportMenuItem": "Export...",
    "home.googleCalendarMenuItem": "Google Calendar...",
    "home.rawCsv": "Raw Data (CSV)",
    "home.patchImport": "Patch Import",
    "home.printPreview": "Print Preview",
    "weekGrid.noDataTitle": "Load timetable data",
    "weekGrid.noDataLine1": "Use Open File or",
    "weekGrid.noDataLine2": "New File from the left sidebar",
    "weekGrid.firstTerm": "First Term",
    "weekGrid.secondTerm": "Second Term",
    "weekGrid.termSuffix": "Term",
    "weekGrid.academicYearSuffix": "Academic Year",
    "weekGrid.weekPatternTitle": "Change this week's pattern",
    "weekGrid.weekPatternChangeTitle": "Tap to change the week pattern",
    "weekGrid.weekA": "Week A",
    "weekGrid.weekB": "Week B",
    "weekGrid.weekC": "Week C",
    "weekGrid.weekD": "Week D",
    "weekGrid.resetAuto": "Return to auto calculation",
    "weekGrid.homeroom": "Homeroom",
    "weekGrid.backToThisWeek": "Back to this week",
    "weekGrid.jumpByDate": "Jump by Date",
    "weekGrid.pickDate": "Select a date",
    "weekGrid.multiSelectActive": "Multi-select",
    "weekGrid.multiSelect": "Multi-select",
    "weekGrid.exitMultiSelect": "Exit multi-select mode",
    "weekGrid.enterMultiSelect": "Edit multiple periods at once",
    "weekGrid.subjectView": "Subject View",
    "weekGrid.classView": "Class View",
    "weekGrid.subjectViewTip": "Subjects are shown larger and classes smaller. Click to switch.",
    "weekGrid.classViewTip": "Classes are shown larger and subjects smaller. Click to switch.",
    "weekGrid.filterByClass": "Filter by Class",
    "weekGrid.classFilter": "Class Filter",
    "weekGrid.filterBySubject": "Filter by Subject",
    "weekGrid.subjectFilter": "Subject Filter",
    "weekGrid.showAll": "Show All",
    "weekGrid.periodTimes": "Period Times",
    "weekGrid.periodTimesSetTip": "Period times are set. Click to edit.",
    "weekGrid.periodTimesTip": "Set start/end times for ICS export",
    "weekGrid.llmImport": "AI (LLM) Import",
    "weekGrid.readFromImage": "Read from Image",
    "weekGrid.timetable": "Timetable",
    "weekGrid.periodTimesShort": "Period Times",
    "weekGrid.annualSchedule": "Annual Schedule",
    "weekGrid.saturdayClass": "Saturday Class",
    "weekGrid.saturdayClassTip": "Show Saturday as a class day for this week only",
    "weekGrid.sundayClass": "Sunday Class",
    "weekGrid.sundayClassTip": "Show Sunday as a class day for this week only",
    "weekGrid.multiSelectMode": "Multi-select Mode",
    "weekGrid.multiSelectHelp": "Tap cells to select, Shift-click for range, Cmd/Ctrl-click to add",
    "weekGrid.selectedSlotsSuffix": "periods selected",
    "weekGrid.release": "Clear",
    "weekGrid.previousWeek": "Previous Week",
    "weekGrid.nextWeek": "Next Week",
    "weekGrid.noData": "No data",
    "weekGrid.schoolClosed": "Closed",
    "weekGrid.periodSuffix": "Period",
    "weekGrid.empty": "Free",
    "weekGrid.legend": "Legend:",
    "weekGrid.gradeSuffix": "Grade",
    "weekGrid.dragSwap": "Drag and drop to swap",
    "weekGrid.longPressSwap": "Long-press to swap",
    "weekGrid.swap": "Swap",
    "weekGrid.todaySchedule": "Today's Classes",
    "weekGrid.noTodayClasses": "No classes today",
    "autoRestore.title": "Restore previous work?",
    "autoRestore.description": "Your previous edits were automatically saved.",
    "autoRestore.fileName": "File name",
    "autoRestore.lastSaved": "Last saved",
    "autoRestore.discard": "Discard and start new",
    "autoRestore.restore": "Restore",
    "confirmChange.title": "Confirm Change",
    "confirmChange.warning": "Warning",
    "confirmChange.cancel": "Cancel",
    "confirmChange.run": "Run",
    "confirmChange.runWithWarnings": "Ignore warning and run",
    "confirmChange.empty": "Free",
    "confirmChange.delete": "Delete",
    "confirmChange.add": "Add",
    "confirmChange.move": "Move",
    "confirmChange.swap": "Swap",
    "semester.add": "Add Semester",
    "semester.semester": "Semester",
    "semester.startDate": "Start Date",
    "semester.endDate": "End Date",
    "semester.copyNotice": "Base timetable and class settings are copied from the current semester.",
    "semester.cancel": "Cancel",
    "semester.addButton": "Add",
    "semester.deleteTitle": "Delete this semester",
    "semester.monthSuffix": "",
    "stats.emptyStats": "Load a file to view statistics",
    "stats.semesterStats": "Semester Stats",
    "stats.annualStats": "Annual Stats",
    "stats.classStats": "Class Stats",
    "stats.subjectStats": "Subject Stats",
    "stats.asOfDate": "As-of Date",
    "stats.backToToday": "Back to today",
    "stats.asOfHelp": "Periods on or before this date are counted as completed",
    "stats.totalPeriods": "Total Periods",
    "stats.annualTotalPeriods": "Annual Total Periods",
    "stats.completed": "Completed",
    "stats.remaining": "Remaining",
    "stats.periodUnit": "periods",
    "stats.semesterTotalSuffix": "terms total",
    "stats.termLowerSingular": "term",
    "stats.termLowerPlural": "terms",
    "stats.class": "Class",
    "stats.total": "Total",
    "stats.totalShort": "Total",
    "stats.doneShort": "Done",
    "stats.remainingShort": "Left",
    "stats.progress": "Progress",
    "stats.noMultiSemester": "No multi-semester data is available",
    "stats.noSubjectData": "No periods have subject information",
    "stats.subjectDataHint": "Set subjects in the class change panel to see subject statistics",
    "history.emptyLoad": "Load a file to view change history",
    "history.noneTitle": "No change history yet",
    "history.noneDescription": "Class changes will appear here",
    "history.title": "Change History",
    "history.undo": "Undo",
    "history.operationCountSuffix": "operations",
    "audit.emptyLoad": "Load a file to view the apply log",
    "audit.title": "Apply Log",
    "audit.warning": "Warnings",
    "audit.error": "Errors",
    "audit.none": "No log entries",
    "audit.periodSuffix": "period",
  },
} as const;

export type TranslationKey = keyof typeof translations.ja;

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

function readStoredLanguage(): Language {
  const stored = localStorage.getItem(STORAGE_KEY);
  return stored === "en" ? "en" : "ja";
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(readStoredLanguage);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage: setLanguageState,
    t: (key) => translations[language][key] ?? translations.ja[key],
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
