import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

// ─────────────────────────────────────────────────────────────────────
//  i18n 用語集 / GLOSSARY（英訳の一貫性のため。新規キー追加時はこれに従う）
// ─────────────────────────────────────────────────────────────────────
//  時間割        = Timetable
//  コマ          = Period (1コマ = 1 period / slot)
//  時限          = Period (1限 = Period 1)
//  授業          = Lesson / Class
//  教科          = Subject
//  学年          = Grade
//  クラス        = Class
//  学級担任      = Homeroom teacher / Homeroom mode
//  教科担任      = Subject teacher
//  指導計画      = Teaching plan
//  単元          = Unit
//  単元マスター  = Unit master
//  内容予定      = Planned content
//  進捗          = Progress
//  実施日        = Date taught / Scheduled date
//  予定          = Event / Schedule (日次イベント = Daily event)
//  年間予定表    = Annual schedule
//  学期          = Term (1学期 = Term 1) / Semester
//  集計          = Stats / Summary
//  休講・休校    = Cancelled / School closed
//  祝日          = Holiday
//  振替          = Reschedule / Swap
//  時程表        = Period times
//  複数選択      = Multi-select
//  上書き/追記   = Overwrite / Append
//  進まなかった  = Behind (delayed) ／ 進みすぎた = Ahead (advanced)
//  非表示/再表示 = Hide / Show
// ─────────────────────────────────────────────────────────────────────

export type Language = "ja" | "en";

const STORAGE_KEY = "timetable_language";

const translations = {
  ja: {
    "app.title": "時間割管理",
    "app.subtitle": "Timetable Manager",
    "common.loading": "読み込み中...",
    "common.save": "保存",
    "common.saved": "保存済み",
    "common.unsaved": "未保存",
    "common.done": "完了",
    "common.error": "エラー",
    "common.cancel": "解除",
    "common.settings": "設定",
    "common.language": "言語",
    "common.japanese": "日本語",
    "common.english": "English",
    "common.justNow": "たった今",
    "common.minutesAgo": "分前",
    "sidebar.newFile": "新規作成",
    "sidebar.openFile": "ファイルを開く",
    "sidebar.saveWithUnsaved": "保存（未保存あり）",
    "sidebar.loadSample": "サンプルデータを読み込む",
    "sidebar.homeroom": "担任",
    "sidebar.notSet": "未設定",
    "sidebar.multiSubject": "複数教科",
    "sidebar.nav.grid": "週間時間割",
    "sidebar.nav.stats": "クラス別集計",
    "sidebar.nav.teachingPlan": "指導計画",
    "sidebar.nav.history": "変更履歴",
    "sidebar.nav.audit": "適用ログ",
    "sidebar.weekNav": "週の移動",
    "sidebar.thisWeek": "今週",
    "sidebar.jumpByDate": "日付で移動",
    "sidebar.pickDate": "移動先の日付を選択",
    "sidebar.undo": "元に戻す",
    "sidebar.export": "エクスポート",
    "sidebar.googleCalendar": "Googleカレンダー連携",
    "sidebar.semesterSettings": "学期設定を変更",
    "sidebar.holidaySettings": "祝日・休校日の設定",
    "sidebar.subjectManagement": "教科の管理",
    "sidebar.mobileMenuStyle": "モバイルメニュー形式",
    "sidebar.mobileBottomSheet": "下から開く",
    "sidebar.mobileSlideLeft": "左から開く",
    "drive.restoring": "ログイン状態を復元中...",
    "drive.loginExpired": "Googleログインが切れました。再ログインしてください。",
    "drive.relogin": "再ログイン",
    "drive.requestCookie": "Cookie許可を要求",
    "drive.requestCookieTitle": "サードパーティCookieの許可をブラウザに要求します",
    "drive.login": "Googleでログイン",
    "drive.syncing": "同期中...",
    "drive.syncedSuffix": " に同期",
    "drive.synced": "同期済み",
    "drive.syncError": "同期エラー",
    "drive.connected": "Drive連携中",
    "drive.disconnect": "解除",
    "drive.reauthTitle": "アカウントの権限を再確認します",
    "drive.logoutTitle": "ログアウト",
    "drive.autoSyncHelp": "✓ 保存のたび自動で同期（隠しフォルダ）",
    "drive.syncOnly": "Drive同期のみ",
    "drive.syncOnlyTitle": "ローカル保存なしで Drive の隠しフォルダだけ更新します",
    "drive.restore": "Driveから復元",
    "drive.backupTitle": "マイドライブ/時間割管理/ に日付付きバックアップを作成",
    "drive.backupToMyDrive": "マイドライブにバックアップ",
    "drive.backupDoneSuffix": " にバックアップ完了",
    "drive.backupFailed": "バックアップ失敗",
    "drive.backupDestination": "→ マイドライブ / 時間割管理 / に保存",
    "drive.backupList": "バックアップ一覧・復元",
    "toast.loaded": "読み込み完了",
    "toast.zipLoaded": "ZIPから読み込み完了",
    "toast.supportedFiles": "対応ファイル: .timetable または .zip",
    "toast.loadError": "読み込みエラー",
    "toast.saved": "保存しました",
    "toast.driveSaved": "Google Driveに保存しました",
    "toast.driveSaveFailed": "Drive保存に失敗しました",
    "toast.backupFailed": "バックアップに失敗しました",
    "toast.driveEmpty": "Google Driveにデータがありませんでした",
    "toast.driveLoaded": "Google Driveから読み込みました",
    "toast.driveLoadFailed": "Drive読み込みに失敗しました",
    "home.titleFallback": "時間割管理",
    "home.saveLocalTitle": "クリックしてローカル保存",
    "home.import": "インポート",
    "home.importTitle": "パッチインポート",
    "home.export": "エクスポート",
    "home.exportTitle": "エクスポート（Excel / PDF / ICS / Google連携 / 生データ）",
    "home.googleLink": "Google連携",
    "home.googleLinkTitle": "Googleカレンダーに直接追加",
    "home.print": "印刷",
    "home.moreActions": "その他の操作",
    "home.exportMenu": "エクスポート",
    "home.exportMenuItem": "エクスポート...",
    "home.googleCalendarMenuItem": "Googleカレンダー連携...",
    "home.rawCsv": "生データ（CSV）",
    "home.patchImport": "パッチインポート",
    "home.printPreview": "印刷プレビュー",
    "weekGrid.noDataTitle": "データを読み込んでください",
    "weekGrid.noDataLine1": "左のサイドバーから「ファイルを開く」または",
    "weekGrid.noDataLine2": "「新規作成」でデータを準備できます",
    "weekGrid.firstTerm": "前期",
    "weekGrid.secondTerm": "後期",
    "weekGrid.termSuffix": "学期",
    "weekGrid.academicYearSuffix": "年度",
    "weekGrid.weekPatternTitle": "この週のパターンを変更",
    "weekGrid.weekPatternChangeTitle": "タップして週パターンを変更",
    "weekGrid.weekA": "A週",
    "weekGrid.weekB": "B週",
    "weekGrid.weekC": "C週",
    "weekGrid.weekD": "D週",
    "weekGrid.resetAuto": "自動計算に戻す",
    "weekGrid.homeroom": "担任",
    "weekGrid.backToThisWeek": "今週に戻る",
    "weekGrid.jumpByDate": "日付で移動",
    "weekGrid.pickDate": "移動先の日付を選択",
    "weekGrid.multiSelectActive": "複数選択中",
    "weekGrid.multiSelect": "複数選択",
    "weekGrid.exitMultiSelect": "複数選択モードを解除",
    "weekGrid.enterMultiSelect": "複数のコマを同時編集するモードに入る",
    "weekGrid.subjectView": "教科ビュー",
    "weekGrid.classView": "クラスビュー",
    "weekGrid.subjectViewTip": "教科を大きく、クラスを小さく表示中。クリックで切り替え",
    "weekGrid.classViewTip": "クラスを大きく、教科を小さく表示中。クリックで切り替え",
    "weekGrid.filterByClass": "クラスで絞り込み",
    "weekGrid.classFilter": "クラスフィルター",
    "weekGrid.filterBySubject": "教科で絞り込み",
    "weekGrid.subjectFilter": "教科フィルター",
    "weekGrid.showAll": "すべて表示",
    "weekGrid.periodTimes": "時程表",
    "weekGrid.periodTimesSetTip": "時程表設定済（クリックで編集）",
    "weekGrid.periodTimesTip": "各コマの開始・終了時刻を設定（ICS書き出し用）",
    "weekGrid.llmImport": "AI(LLM)読み取り",
    "weekGrid.readFromImage": "画像から読み取る",
    "weekGrid.timetable": "時間割",
    "weekGrid.periodTimesShort": "時程表",
    "weekGrid.annualSchedule": "年間予定表",
    "weekGrid.saturdayClass": "土曜授業",
    "weekGrid.saturdayClassTip": "この週のみ土曜日を授業日として表示",
    "weekGrid.sundayClass": "日曜授業",
    "weekGrid.sundayClassTip": "この週のみ日曜日を授業日として表示",
    "weekGrid.lessonPlanOff": "指導計画の表示をOFF",
    "weekGrid.lessonPlanOn": "セルに指導計画の内容を表示",
    "weekGrid.weekendClass": "土日授業",
    "weekGrid.weekendPopoverTitle": "この週だけ追加表示する曜日",
    "weekGrid.weekendClassTip": "この週のみ土曜日・日曜日を授業日として表示します",
    "weekGrid.eventsRow": "予定",
    "weekGrid.satShort": "土",
    "weekGrid.sunShort": "日",
    "weekGrid.multiSelectMode": "複数選択モード",
    "weekGrid.multiSelectHelp": "セルをタップで選択、Shift+クリックで範囲選択、Cmd/Ctrl+クリックで追加選択",
    "weekGrid.selectedSlotsSuffix": "コマ選択中",
    "weekGrid.release": "解除",
    "weekGrid.previousWeek": "前の週",
    "weekGrid.nextWeek": "次の週",
    "weekGrid.noData": "データなし",
    "weekGrid.schoolClosed": "休校",
    "weekGrid.periodSuffix": "限",
    "weekGrid.empty": "空き",
    "weekGrid.legend": "凡例:",
    "weekGrid.gradeSuffix": "年",
    "weekGrid.dragSwap": "ドラッグ＆ドロップで交換",
    "weekGrid.longPressSwap": "長押しでドラッグ交換",
    "weekGrid.swap": "交換",
    "weekGrid.todaySchedule": "本日の授業予定",
    "weekGrid.noTodayClasses": "本日の授業はありません",
    "autoRestore.title": "前回の作業を復元しますか？",
    "autoRestore.description": "前回の編集内容が自動保存されています。",
    "autoRestore.fileName": "ファイル名",
    "autoRestore.lastSaved": "最終保存",
    "autoRestore.discard": "破棄して新規",
    "autoRestore.restore": "復元する",
    "confirmChange.title": "変更の確認",
    "confirmChange.warning": "警告",
    "confirmChange.cancel": "キャンセル",
    "confirmChange.run": "実行",
    "confirmChange.runWithWarnings": "警告を無視して実行",
    "confirmChange.empty": "空き",
    "confirmChange.delete": "削除",
    "confirmChange.add": "追加",
    "confirmChange.move": "移動",
    "confirmChange.swap": "交換",
    "semester.add": "学期を追加",
    "semester.semester": "学期",
    "semester.startDate": "始業日",
    "semester.endDate": "終業日",
    "semester.copyNotice": "基本時間割・クラス設定は現在の学期から引き継がれます。",
    "semester.cancel": "キャンセル",
    "semester.addButton": "追加",
    "semester.deleteTitle": "この学期を削除",
    "semester.monthSuffix": "月",
    "stats.emptyStats": "ファイルを読み込むと集計が表示されます",
    "stats.semesterStats": "学期別集計",
    "stats.annualStats": "年間集計",
    "stats.classStats": "クラス別集計",
    "stats.subjectStats": "教科別集計",
    "stats.asOfDate": "集計基準日",
    "stats.backToToday": "今日に戻す",
    "stats.asOfHelp": "※ この日付以前を「実施済み」として集計します",
    "stats.totalPeriods": "総コマ数",
    "stats.annualTotalPeriods": "年間総コマ数",
    "stats.completed": "実施済み",
    "stats.remaining": "残り",
    "stats.periodUnit": "コマ",
    "stats.semesterTotalSuffix": "学期合計",
    "stats.termLowerSingular": "学期",
    "stats.termLowerPlural": "学期",
    "stats.class": "クラス",
    "stats.total": "合計",
    "stats.totalShort": "計",
    "stats.doneShort": "済",
    "stats.remainingShort": "残",
    "stats.progress": "進捗",
    "stats.noMultiSemester": "複数学期のデータがありません",
    "stats.noSubjectData": "教科情報のあるコマがありません",
    "stats.subjectDataHint": "授業変更パネルからコマに教科を設定すると集計されます",
    "stats.filterBySubject": "教科で絞り込み",
    "stats.allSubjects": "すべての教科（合計）",
    "stats.onlySubjectBadge": "「{s}」のみで各クラスの進捗を集計中",
    "history.emptyLoad": "ファイルを読み込むと変更履歴が表示されます",
    "history.noneTitle": "変更履歴はまだありません",
    "history.noneDescription": "授業変更を行うと、ここに履歴が表示されます",
    "history.title": "変更履歴",
    "history.undo": "元に戻す",
    "history.operationCountSuffix": "件の操作",
    "audit.emptyLoad": "ファイルを読み込むと適用ログが表示されます",
    "audit.title": "適用ログ",
    "audit.warning": "警告",
    "audit.error": "エラー",
    "audit.none": "ログはありません",
    "audit.periodSuffix": "限",
    "inspector.multiSelectMode": "複数選択モード",
    "inspector.selectPeriodsPrompt": "コマを選択してください",
    "inspector.nSelected": "{n}コマ選択中",
    "inspector.othersCount": "...他 {n} コマ",
    "inspector.clearAll": "選択をすべて解除",
    "inspector.opDelete": "削除",
    "inspector.opAdd": "追加",
    "inspector.opMove": "移動",
    "inspector.opSwap": "交換",
    "inspector.opReason": "理由",
    "inspector.opSubject": "教科",
    "inspector.batchDeleteDesc": "選択した {n}コマ の授業を削除します",
    "inspector.batchAddDesc": "選択した {n}コマ に一括追加します",
    "inspector.batchReasonDesc": "選択した {n}コマ に理由を一括設定します",
    "inspector.batchSubjectDesc": "選択した {n}コマ の教科を一括設定します",
    "inspector.classLabel": "クラス",
    "inspector.homeroomHint": "(担任: {c})",
    "inspector.notSet": "未設定",
    "inspector.selectClassPlaceholder": "クラスを選択...",
    "inspector.noneSelectable": "— 指定なし —",
    "inspector.notSpecified": "指定なし",
    "inspector.subjectNoneDelete": "教科なし（削除）",
    "inspector.execDelete": "{n}コマを削除",
    "inspector.execAdd": "{n}コマに追加",
    "inspector.execReason": "{n}コマに理由を設定",
    "inspector.execSubject": "{n}コマの教科を設定",
    "inspector.selectedCell": "選択中のコマ",
    "inspector.empty": "空き",
    "inspector.errNoSelection": "コマが選択されていません",
    "inspector.errClassOrSubject": "クラスまたは教科を指定してください",
    "inspector.errEnterReason": "理由を入力してください",
    "inspector.errSelectMoveDate": "移動先の日付を選択してください",
    "inspector.errSelectSwapDate": "交換先の日付を選択してください",
    "inspector.okBatchDeleted": "{n}コマを削除しました",
    "inspector.okBatchAdded": "{n}コマに「{label}」を追加しました",
    "inspector.okBatchReason": "{n}コマに理由を設定しました",
    "inspector.okBatchSubjectSet": "{n}コマの教科を「{label}」に設定しました",
    "inspector.okBatchSubjectDeleted": "{n}コマの教科を削除しました",
    "inspector.okDeleted": "削除しました: {d}",
    "inspector.okAdded": "追加しました: {label}",
    "inspector.okMoved": "移動しました",
    "inspector.okSwapped": "交換しました",
    "inspector.okReasonSet": "理由を設定しました",
    "inspector.okSubjectSet": "教科を「{label}」に設定しました",
    "inspector.okSubjectDeleted": "教科を削除しました",
    "inspector.descDelete": "{d} の授業を削除します",
    "inspector.descAdd": "{d} に授業を追加します",
    "inspector.descMove": "{from} を {to} に移動します",
    "inspector.descSwap": "{a} と {b} を交換します",
    "inspector.descReason": "{d} の理由を設定します",
    "inspector.descSubject": "{d} の教科を設定します",
    "inspector.moveFrom": "移動元",
    "inspector.moveTo": "移動先",
    "inspector.moveOverwriteWarn": "移動先 ({to}) には {c} が入っています。上書きされます。",
    "inspector.none": "なし",
    "inspector.noClass": "授業なし",
    "inspector.subjectPrefix": "教科: {s}",
    "inspector.emptyPeriod": "空きコマ",
    "inspector.deleteTargetSuffix": "を削除します",
    "inspector.selectClassBlankHint": "クラスを選択...　(空白=指定なし)",
    "inspector.specifyMoveDest": "移動先を指定してください",
    "inspector.specifySwapDest": "交換先を指定してください",
    "inspector.swapTo": "交換先",
    "inspector.moveDestOccupied": "⚠ 移動先に {c} が入っています（上書きされます）",
    "inspector.reasonOverwriteNote": "理由を設定します（既存の理由を上書き）",
    "inspector.currentSubjectHint": "(現在: {s})",
    "inspector.confirmDelete": "削除を確認",
    "inspector.confirmAdd": "追加を確認",
    "inspector.confirmMove": "移動を確認",
    "inspector.confirmSwap": "交換を確認",
    "inspector.confirmReason": "理由を設定",
    "inspector.confirmSubject": "教科を設定",
    "inspector.reasonField": "理由",
    "inspector.subjectField": "教科",
    "inspector.optional": "(任意)",
    "inspector.reasonPlaceholder": "理由を入力...",
    "inspector.subjectNone": "教科なし",
    "inspector.selectSubjectPlaceholder": "教科を選択...",
    "inspector.dateOf": "{label}の日付",
    "inspector.periodOf": "{label}の時限",
    "inspector.selectDatePlaceholder": "日付を選択...",
    "inspector.setSubjectForCell": "このコマの教科を設定します",
    "dayEvents.cat.ceremony": "式典",
    "dayEvents.cat.event": "行事",
    "dayEvents.cat.work": "業務",
    "dayEvents.cat.student": "学級",
    "dayEvents.cat.holiday": "休日",
    "dayEvents.cat.other": "その他",
    "dayEvents.hint.ceremony": "始業式・入学式・卒業式",
    "dayEvents.hint.event": "運動会・遠足・参観日・全校集会",
    "dayEvents.hint.work": "職員会議・研修・PTA",
    "dayEvents.hint.student": "懇談・家庭訪問・避難訓練・健康診断",
    "dayEvents.hint.holiday": "休校日・祝日",
    "dayEvents.hint.other": "上記以外",
    "dayEvents.contentPlaceholder": "予定の内容（例: 職員会議）",
    "dayEvents.custom": "カスタム:",
    "dayEvents.newTagPlaceholder": "新しいタグ",
    "dayEvents.add": "追加",
    "dayEvents.save": "保存",
    "dayEvents.cancel": "キャンセル",
    "dayEvents.addCustomCategory": "独自のカテゴリを追加",
    "dayEvents.new": "新規",
    "dayEvents.customTagLabel": "カスタムタグ「{c}」",
    "dayEvents.addCustomTagLink": "+ カスタムタグを追加",
    "dayEvents.notePlaceholder": "メモ（任意）",
    "dayEvents.delete": "削除",
    "dayEvents.editTitle": "予定を編集 — {date}",
    "dayEvents.addEventTitle": "予定を追加",
    "dayEvents.addEventHeader": "予定を追加 — {date}",
    "dayEvents.eventsShort": "予定",
    "dayEvents.weekEvents": "この週の予定",
    "dayEvents.countSuffix": "（{n}件）",
    "dayEvents.weekdays": "日,月,火,水,木,金,土",
    "tp.notHeld": "実施なし",
    "tp.noneBackToPlan": "— なし（計画に戻す）",
    "tp.planMark": "計",
    "tp.unitCellAuto": "自動計画（クリックで手動変更）",
    "tp.unitCellClick": "クリックして単元を変更",
    "tp.setUnit": "単元を設定…",
    "tp.unitEditorHint": "単元を順番に並べ、計画コマ数を設定すると自動割り振りされます。▶で単元の各時間を編集できます。",
    "tp.totalKoma": "計 {n}コマ",
    "tp.komaUnit": "コマ",
    "tp.filledCount": "({n}件記入済)",
    "tp.unitMasterHint": "この単元の各時間で何をするか（マスター予定）。ここで編集すると、コマ単位リストに薄字で反映されます。",
    "tp.periodNo": "{p}時",
    "tp.periodContentPlaceholder": "{p}時目の内容（例: 導入・練習・まとめ）",
    "tp.newUnit": "新しい単元",
    "tp.addUnit": "単元を追加",
    "tp.editUnitPeriods": "単元の各時間を編集",
    "tp.closeEdit": "閉じる",
    "tp.skipDesc": "実施なし（計画コマカウントから除外）",
    "tp.notStarted": "未開始",
    "tp.done": "完了",
    "tp.todayMark": "▶ 今日",
    "tp.nextMark": "→ 次回",
    "tp.overflow": "日程超過",
    "tp.overflowParen": " (日程超過)",
    "tp.behindShort": " ⚠進まず",
    "tp.advancedShort": " ⏩前倒し",
    "tp.contentPlaceholder": "内容予定",
    "tp.unitMasterPrefix": "単元マスター: {c}",
    "tp.unitMasterClickOverride": "単元マスター: {c}（クリックで上書き）",
    "tp.notesPlaceholder": "備考（任意）",
    "tp.save": "保存",
    "tp.cancelEdit": "取消",
    "tp.clickToInput": "クリックして入力…",
    "tp.classOnlyContent": "このクラスだけの実施内容（任意）",
    "tp.classOnlyContentPh": "例: 復習に充てた / p.42まで",
    "tp.classNote": "クラス固有メモ",
    "tp.classNotePh": "例: 耳鼻科検診で半分のみ",
    "tp.contentOverrideMark": "内容上書きあり",
    "tp.noteExists": "メモあり ",
    "tp.behindLabel": "進まなかった ",
    "tp.advancedLabel": "前のコマと同日に実施(前倒し) ",
    "tp.cellClickHint": "{cls}: クリックでメモ・進捗マーク",
    "tp.overflowTip": "{cls}: 繰越により読み込み済み時間割の範囲を超えました（時間割を先の週まで進めると実施日が確定します）",
    "tp.behindToOverflow": "{from}で進まず→{d}に繰越 ",
    "tp.carriedOver": "{from} に進まなかったため、この行は {to} に繰り越されています。後続のコマも1つずつ後ろにずれます。",
    "tp.unitMgmt": "単元管理",
    "tp.unitMgmtEmptyHint": "（単元を追加すると各コマに割り当てられます）",
    "tp.allKoma": "全{n}コマ",
    "tp.planAutoAssign": "計画{n}コマ自動割り振り",
    "tp.komaFilled": "{n}コマ入力済み",
    "tp.komaNotHeld": "{n}コマ実施なし",
    "tp.targetClasses": "対象クラス: {c}",
    "tp.opHint": "単元セルをクリック → 単元を変更 ／ 内容予定をクリック → 編集（薄字は単元マスター） ／ 計画行数の変更は単元管理パネルでコマ数を調整 ／ ",
    "tp.opHintClass": "クラスの実施日セルをクリック → そのクラスだけ「進まなかった」マーク・メモ追加",
    "tp.colUnit": "単元",
    "tp.colUnitInner": "単元内",
    "tp.colContent": "内容予定",
    "tp.noTimetableData": "時間割にデータがありません。週間時間割でコマを追加すると自動で表示されます。",
    "tp.manualAddTitle": "手動で学年×教科を追加",
    "tp.manualAddDesc": "時間割に存在しない組み合わせを手動で追加します",
    "tp.gradeLabel": "学年（例: 5年）",
    "tp.subjectLabel": "教科（例: 理科）",
    "tp.gradePh": "5年",
    "tp.subjectPh": "理科",
    "tp.alreadyExists": "この組み合わせはすでに存在します",
    "tp.cancel": "キャンセル",
    "tp.add": "追加",
    "tp.classLabel": "クラス",
    "tp.asOfLabel": "基準日",
    "tp.todayBtn": "今日",
    "tp.viewLabel": "表示（複数可）",
    "tp.fieldUnit": "単元名",
    "tp.fieldContent": "内容",
    "tp.fieldDate": "日付",
    "tp.legendDone": "済",
    "tp.legendToday": "今日",
    "tp.legendNext": "次回",
    "tp.legendNotYet": "未",
    "tp.legendBehind": "遅延",
    "tp.legendAhead": "前倒し",
    "tp.legendOverflow": "日程超過",
    "tp.noClassSubjectData": "このクラスの教科データがありません",
    "tp.colSubject": "教科",
    "tp.colProgress": "進捗",
    "tp.colCurrent": "現在地",
    "tp.colNext": "次の予定",
    "tp.colNextDate": "次回日付",
    "tp.colChart": "進捗チャート",
    "tp.openSubjectPlan": "この教科の指導計画を開く",
    "tp.unitNotSet": "（単元未設定）",
    "tp.contentNotEntered": "（内容未入力）",
    "tp.jumpHint": "教科名をクリックすると、その教科の指導計画（単元×コマ表）へ移動します。",
    "tp.gradeSubject": "学年 × 教科",
    "tp.notEntered": "未入力",
    "tp.manualAdded": "手動追加",
    "tp.komaCountSuffix": "コマ",
    "tp.hiddenN": "非表示（{n}）",
    "tp.allGradesHiddenN": "全学年非表示（{n}）",
    "tp.allGrades": "全学年",
    "tp.allGradesParen": "（全学年）",
    "tp.tabHomeroom": "クラス別（学級担任）",
    "tp.tabSubject": "教科別（指導計画編集）",
    "tp.selectGradeSubject": "左から学年×教科を選択してください",
    "tp.deleteThisPlan": "この指導計画のデータを削除",
    "tp.deleteConfirmTitle": "指導計画データを削除しますか？",
    "tp.deleteConfirmBody": "入力した授業内容・単元データがすべて削除されます。この操作は取り消せません。",
    "tp.delete": "削除",
    "tp.loadFilePrompt": "ファイルを読み込んでください",
    "tp.noSubjectData": "時間割に教科データがありません",
    "tp.hideThisCombo": "「{g} {s}」を指導計画一覧から非表示にする",
    "tp.showThisCombo": "「{g} {s}」を再表示",
    "tp.hideAllGrades": "「{s}」を全学年で非表示にする",
    "tp.showAllGrades": "「{s}」を全学年で再表示",
    "tp.manualAddBtn": "手動で追加",
    "tp.chartCellTitle": "{n}時 {unit}",
    "tp.behindArrow": "↓進まず",
    "tp.carriedOverInfo": "{from} に進まなかったため、この行は {to} に繰り越されています。後続のコマも1つずつ後ろにずれます。",
    "tp.advancedInfo": "前のコマと同じ日にまとめて実施（1日2コマ）。この行以降が1つずつ前にずれます。",
    "tp.overflowInfo": "繰越の累積により、読み込み済みの時間割の範囲を超えました。週送りで先まで時間割を表示すると実施日が確定します（時間割の予備コマが足りない場合は計画調整が必要です）。",
    "tp.behindCheckbox": "進まなかった",
    "tp.behindCheckboxHint": "授業は実施したが、計画通り進められなかった（→後続が後ろにずれる）",
    "tp.advancedCheckbox": "進みすぎた（前倒し）",
    "tp.advancedCheckboxHint": "前のコマと同じ日にまとめて実施した（→後続が前にずれる）",
    "tp.classContentEmptyHint": "空欄なら計画の「内容予定」が適用されます",
    "tp.clearAll": "すべて解除",
    "tp.itemsCount": "{n}件",
    "tp.completedFraction": "{a}/{b}完了",
    "tp.behindBy": "-{n}遅れ",
    "tp.markLegend": "▶ = 今日　→ = 次回　✓ = 済み",
    "llm.templateAppend": "\n\n--- 以下のJSONテンプレートに記入して返してください ---\n",
    "llm.errPasteJson": "JSONを貼り付けてください。",
    "llm.infoTimetableChecked": "時間割JSONを確認しました。「インポート」ボタン（ツールバー）からパッチインポートで読み込んでください。",
    "llm.errJsonFormat": "JSONの形式が正しくありません。LLMの出力をそのままコピーしてください。",
    "llm.errPeriodTimesFormat": "時程表JSONの形式が正しくありません。LLMの出力をそのままコピーしてください。",
    "llm.okPeriodTimesUpdated": "時程表を更新しました。",
    "llm.errScheduleFormat": "年間予定表JSONの形式が正しくありません。events配列またはops配列を含むJSONをコピーしてください。",
    "llm.errNothingToApply": "適用すべき予定・操作が見つかりませんでした。",
    "llm.replacedWithEvents": "{n}件の予定で置換",
    "llm.removedOld": "旧{n}件削除",
    "llm.classChanges": "{n}件の授業変更",
    "llm.eventsAppended": "{n}件の予定を追記",
    "llm.applied": "適用しました",
    "llm.infoNothingToAdd": "追加する予定がありませんでした",
    "llm.appendSummary": "{added}件追記",
    "llm.skippedSuffix": "・{n}件スキップ",
    "llm.classChangesSuffix": "・{n}件の授業変更",
    "llm.modeTimetable": "時間割",
    "llm.descTimetable": "週間時間割の画像からクラス配置を読み取ります。",
    "llm.phTimetable": "LLMが出力したJSONをここに貼り付けてください...",
    "llm.noteTimetable": "※ 時間割JSONはパッチインポート（ツールバー「インポート」）で適用してください。",
    "llm.modePeriodTimes": "時程表",
    "llm.descPeriodTimes": "時程表の画像から各コマの開始・終了時刻を読み取ります。",
    "llm.phPeriodTimes": "LLMが出力した時程表JSONをここに貼り付けてください...",
    "llm.notePeriodTimes": "「適用」ボタンを押すと時程表が更新されます。",
    "llm.modeSchedule": "年間予定表",
    "llm.descSchedule": "年間予定表の画像から行事・休講情報を読み取り、時間割に適用します。",
    "llm.phSchedule": "LLMが出力した年間予定表JSONをここに貼り付けてください...",
    "llm.noteSchedule": "「適用」ボタンを押すと行事・休講情報が時間割に反映されます。",
    "llm.dialogTitle": "AI（LLM）で画像から読み取る",
    "llm.dialogDesc": "生成AI（LLM＝ChatGPT、Claude、Geminiなど）を使って、時間割・時程表・年間予定表の画像から自動でデータを入力できます。",
    "llm.scopeLabel": "取込スコープ",
    "llm.scopeWithOps": "コマ削除等も含む",
    "llm.scopeWithOpsDesc": "ルールに基づき授業もカット",
    "llm.scopeEventsOnly": "予定欄だけ",
    "llm.scopeEventsOnlyDesc": "授業コマは一切変更しない（安全）",
    "llm.modeLabel": "取込モード",
    "llm.modeAppend": "追記",
    "llm.modeAppendDesc": "既存予定を残し追加（重複確認あり）",
    "llm.modeOverwrite": "上書き",
    "llm.modeOverwriteDesc": "取込日付範囲の予定を置換",
    "llm.clearAllPrefix": "既存予定を",
    "llm.clearAllWord": "全クリア",
    "llm.clearAllSuffix": "してから総入れ替え（日付範囲に限定しない）",
    "llm.scopeNoteProtected": "✓ 授業コマは保護されます。予定欄のみ更新。",
    "llm.scopeNoteCut": "⚠ ルール該当行事は授業コマも削除されます。",
    "llm.modeNoteAppend": " 追記＝既存を消さず追加。",
    "llm.modeNoteOverwriteAll": " 上書き＝既存を全削除して総入替。",
    "llm.modeNoteOverwriteRange": " 上書き＝取込日付範囲の既存予定のみ置換（範囲外は保持）。",
    "llm.stepRuleTitle": "授業カットの個別ルールを入力（任意）",
    "llm.stepRuleDesc": "行事ごとの休講ルールをLLMに伝えます。例：「運動会は全コマ休講」「校外学習は4限まで授業なし、5・6限は授業あり」",
    "llm.stepRulePh": "例: 運動会は全コマ休講。校外学習は4限まで授業なし、5・6限は授業あり。...",
    "llm.stepPromptTitle": "LLM向けプロンプトをコピー",
    "llm.stepPromptDesc": "JSONテンプレートも含まれています。これ1つをLLMに貼り付ければOKです。",
    "llm.copied": "コピーしました",
    "llm.copyPromptWithTemplate": "プロンプトをコピー（テンプレ込み）",
    "llm.advanced": "上級者向け:",
    "llm.copyTemplateOnly": "JSONテンプレートのみコピー",
    "llm.download": "ダウンロード",
    "llm.stepPasteTitle": "AIに画像と一緒に貼り付け",
    "llm.stepPasteDesc": "ChatGPT・Claude・Geminiなどを開き、コピーした「プロンプト（テンプレ込み）」と「画像」を貼り付けて送信します。",
    "llm.stepImportTitle": "LLMが返したJSONを貼り付けて適用",
    "llm.appliedDone": "適用しました。",
    "llm.dupTitle": "重複の可能性がある予定が {n} 件あります",
    "llm.dupDesc": "同じ日付に似た予定が既にあります。チェックを入れたものだけ追加します（重複は既定でスキップ）。",
    "llm.dupAddAll": "すべて追加",
    "llm.dupSkipAll": "すべてスキップ",
    "llm.dupExisting": " ↔ 既存「{title}」",
    "llm.dupConfirmAppend": "確定して追記",
    "llm.cancel": "キャンセル",
    "llm.dupAutoAdd": "重複なしの {n} 件は自動追加されます。",
    "llm.apply": "適用する",
    "llm.hintLabel": "ヒント:",
    "llm.hintBody": " GPT-4o・Claude 3.5 Sonnet等の画像対応モデルを使うと精度が上がります。読み取り結果は必ず確認してから保存してください。",
    "llm.hintSchedule": " 年間予定表は複雑なため、適用後に変更履歴で内容を確認することをお勧めします。",
    "llm.close": "閉じる",
  },
  en: {
    "app.title": "Timetable Manager",
    "app.subtitle": "Timetable Manager",
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.saved": "Saved",
    "common.unsaved": "Unsaved",
    "common.done": "Done",
    "common.error": "Error",
    "common.cancel": "Disconnect",
    "common.settings": "Settings",
    "common.language": "Language",
    "common.japanese": "Japanese",
    "common.english": "English",
    "common.justNow": "Just now",
    "common.minutesAgo": "min ago",
    "sidebar.newFile": "New File",
    "sidebar.openFile": "Open File",
    "sidebar.saveWithUnsaved": "Save (unsaved changes)",
    "sidebar.loadSample": "Load sample data",
    "sidebar.homeroom": "Homeroom",
    "sidebar.notSet": "Not set",
    "sidebar.multiSubject": "Multiple subjects",
    "sidebar.nav.grid": "Weekly Timetable",
    "sidebar.nav.stats": "Class Stats",
    "sidebar.nav.teachingPlan": "Teaching Plan",
    "sidebar.nav.history": "Change History",
    "sidebar.nav.audit": "Apply Log",
    "sidebar.weekNav": "Week Navigation",
    "sidebar.thisWeek": "This Week",
    "sidebar.jumpByDate": "Jump by Date",
    "sidebar.pickDate": "Select a date",
    "sidebar.undo": "Undo",
    "sidebar.export": "Export",
    "sidebar.googleCalendar": "Google Calendar",
    "sidebar.semesterSettings": "Semester Settings",
    "sidebar.holidaySettings": "Holidays / School Closures",
    "sidebar.subjectManagement": "Manage Subjects",
    "sidebar.mobileMenuStyle": "Mobile Menu Style",
    "sidebar.mobileBottomSheet": "Bottom Sheet",
    "sidebar.mobileSlideLeft": "Slide from Left",
    "drive.restoring": "Restoring login...",
    "drive.loginExpired": "Google login expired. Please sign in again.",
    "drive.relogin": "Sign in again",
    "drive.requestCookie": "Request cookie access",
    "drive.requestCookieTitle": "Request browser permission for third-party cookie access",
    "drive.login": "Sign in with Google",
    "drive.syncing": "Syncing...",
    "drive.syncedSuffix": " synced",
    "drive.synced": "Synced",
    "drive.syncError": "Sync error",
    "drive.connected": "Drive connected",
    "drive.disconnect": "Disconnect",
    "drive.reauthTitle": "Reconfirm account permissions",
    "drive.logoutTitle": "Sign out",
    "drive.autoSyncHelp": "Auto-sync on every save (hidden folder)",
    "drive.syncOnly": "Sync to Drive only",
    "drive.syncOnlyTitle": "Update only the hidden Drive copy without local save",
    "drive.restore": "Restore from Drive",
    "drive.backupTitle": "Create a dated backup in My Drive/Timetable Manager/",
    "drive.backupToMyDrive": "Back up to My Drive",
    "drive.backupDoneSuffix": " backup complete",
    "drive.backupFailed": "Backup failed",
    "drive.backupDestination": "Saved to My Drive / Timetable Manager /",
    "drive.backupList": "Backup List / Restore",
    "toast.loaded": "Loaded",
    "toast.zipLoaded": "Loaded from ZIP",
    "toast.supportedFiles": "Supported files: .timetable or .zip",
    "toast.loadError": "Load error",
    "toast.saved": "Saved",
    "toast.driveSaved": "Saved to Google Drive",
    "toast.driveSaveFailed": "Failed to save to Drive",
    "toast.backupFailed": "Backup failed",
    "toast.driveEmpty": "No data found in Google Drive",
    "toast.driveLoaded": "Loaded from Google Drive",
    "toast.driveLoadFailed": "Failed to load from Drive",
    "home.titleFallback": "Timetable Manager",
    "home.saveLocalTitle": "Click to save locally",
    "home.import": "Import",
    "home.importTitle": "Patch import",
    "home.export": "Export",
    "home.exportTitle": "Export (Excel / PDF / ICS / Google / Raw data)",
    "home.googleLink": "Google",
    "home.googleLinkTitle": "Add directly to Google Calendar",
    "home.print": "Print",
    "home.moreActions": "More actions",
    "home.exportMenu": "Export",
    "home.exportMenuItem": "Export...",
    "home.googleCalendarMenuItem": "Google Calendar...",
    "home.rawCsv": "Raw Data (CSV)",
    "home.patchImport": "Patch Import",
    "home.printPreview": "Print Preview",
    "weekGrid.noDataTitle": "Load timetable data",
    "weekGrid.noDataLine1": "Use Open File or",
    "weekGrid.noDataLine2": "New File from the left sidebar",
    "weekGrid.firstTerm": "First Term",
    "weekGrid.secondTerm": "Second Term",
    "weekGrid.termSuffix": "Term",
    "weekGrid.academicYearSuffix": "Academic Year",
    "weekGrid.weekPatternTitle": "Change this week's pattern",
    "weekGrid.weekPatternChangeTitle": "Tap to change the week pattern",
    "weekGrid.weekA": "Week A",
    "weekGrid.weekB": "Week B",
    "weekGrid.weekC": "Week C",
    "weekGrid.weekD": "Week D",
    "weekGrid.resetAuto": "Return to auto calculation",
    "weekGrid.homeroom": "Homeroom",
    "weekGrid.backToThisWeek": "Back to this week",
    "weekGrid.jumpByDate": "Jump by Date",
    "weekGrid.pickDate": "Select a date",
    "weekGrid.multiSelectActive": "Multi-select",
    "weekGrid.multiSelect": "Multi-select",
    "weekGrid.exitMultiSelect": "Exit multi-select mode",
    "weekGrid.enterMultiSelect": "Edit multiple periods at once",
    "weekGrid.subjectView": "Subject View",
    "weekGrid.classView": "Class View",
    "weekGrid.subjectViewTip": "Subjects are shown larger and classes smaller. Click to switch.",
    "weekGrid.classViewTip": "Classes are shown larger and subjects smaller. Click to switch.",
    "weekGrid.filterByClass": "Filter by Class",
    "weekGrid.classFilter": "Class Filter",
    "weekGrid.filterBySubject": "Filter by Subject",
    "weekGrid.subjectFilter": "Subject Filter",
    "weekGrid.showAll": "Show All",
    "weekGrid.periodTimes": "Period Times",
    "weekGrid.periodTimesSetTip": "Period times are set. Click to edit.",
    "weekGrid.periodTimesTip": "Set start/end times for ICS export",
    "weekGrid.llmImport": "AI (LLM) Import",
    "weekGrid.readFromImage": "Read from Image",
    "weekGrid.timetable": "Timetable",
    "weekGrid.periodTimesShort": "Period Times",
    "weekGrid.annualSchedule": "Annual Schedule",
    "weekGrid.saturdayClass": "Saturday Class",
    "weekGrid.saturdayClassTip": "Show Saturday as a class day for this week only",
    "weekGrid.sundayClass": "Sunday Class",
    "weekGrid.sundayClassTip": "Show Sunday as a class day for this week only",
    "weekGrid.lessonPlanOff": "Hide teaching plan",
    "weekGrid.lessonPlanOn": "Show teaching plan in cells",
    "weekGrid.weekendClass": "Weekend Class",
    "weekGrid.weekendPopoverTitle": "Extra days to show this week only",
    "weekGrid.weekendClassTip": "Show Saturday and Sunday as class days for this week only",
    "weekGrid.eventsRow": "Events",
    "weekGrid.satShort": "Sat",
    "weekGrid.sunShort": "Sun",
    "weekGrid.multiSelectMode": "Multi-select Mode",
    "weekGrid.multiSelectHelp": "Tap cells to select, Shift-click for range, Cmd/Ctrl-click to add",
    "weekGrid.selectedSlotsSuffix": "periods selected",
    "weekGrid.release": "Clear",
    "weekGrid.previousWeek": "Previous Week",
    "weekGrid.nextWeek": "Next Week",
    "weekGrid.noData": "No data",
    "weekGrid.schoolClosed": "Closed",
    "weekGrid.periodSuffix": "Period",
    "weekGrid.empty": "Free",
    "weekGrid.legend": "Legend:",
    "weekGrid.gradeSuffix": "Grade",
    "weekGrid.dragSwap": "Drag and drop to swap",
    "weekGrid.longPressSwap": "Long-press to swap",
    "weekGrid.swap": "Swap",
    "weekGrid.todaySchedule": "Today's Classes",
    "weekGrid.noTodayClasses": "No classes today",
    "autoRestore.title": "Restore previous work?",
    "autoRestore.description": "Your previous edits were automatically saved.",
    "autoRestore.fileName": "File name",
    "autoRestore.lastSaved": "Last saved",
    "autoRestore.discard": "Discard and start new",
    "autoRestore.restore": "Restore",
    "confirmChange.title": "Confirm Change",
    "confirmChange.warning": "Warning",
    "confirmChange.cancel": "Cancel",
    "confirmChange.run": "Run",
    "confirmChange.runWithWarnings": "Ignore warning and run",
    "confirmChange.empty": "Free",
    "confirmChange.delete": "Delete",
    "confirmChange.add": "Add",
    "confirmChange.move": "Move",
    "confirmChange.swap": "Swap",
    "semester.add": "Add Semester",
    "semester.semester": "Semester",
    "semester.startDate": "Start Date",
    "semester.endDate": "End Date",
    "semester.copyNotice": "Base timetable and class settings are copied from the current semester.",
    "semester.cancel": "Cancel",
    "semester.addButton": "Add",
    "semester.deleteTitle": "Delete this semester",
    "semester.monthSuffix": "",
    "stats.emptyStats": "Load a file to view statistics",
    "stats.semesterStats": "Semester Stats",
    "stats.annualStats": "Annual Stats",
    "stats.classStats": "Class Stats",
    "stats.subjectStats": "Subject Stats",
    "stats.asOfDate": "As-of Date",
    "stats.backToToday": "Back to today",
    "stats.asOfHelp": "Periods on or before this date are counted as completed",
    "stats.totalPeriods": "Total Periods",
    "stats.annualTotalPeriods": "Annual Total Periods",
    "stats.completed": "Completed",
    "stats.remaining": "Remaining",
    "stats.periodUnit": "periods",
    "stats.semesterTotalSuffix": "terms total",
    "stats.termLowerSingular": "term",
    "stats.termLowerPlural": "terms",
    "stats.class": "Class",
    "stats.total": "Total",
    "stats.totalShort": "Total",
    "stats.doneShort": "Done",
    "stats.remainingShort": "Left",
    "stats.progress": "Progress",
    "stats.noMultiSemester": "No multi-semester data is available",
    "stats.noSubjectData": "No periods have subject information",
    "stats.subjectDataHint": "Set subjects in the class change panel to see subject statistics",
    "stats.filterBySubject": "Filter by subject",
    "stats.allSubjects": "All subjects (total)",
    "stats.onlySubjectBadge": "Showing per-class progress for “{s}” only",
    "history.emptyLoad": "Load a file to view change history",
    "history.noneTitle": "No change history yet",
    "history.noneDescription": "Class changes will appear here",
    "history.title": "Change History",
    "history.undo": "Undo",
    "history.operationCountSuffix": "operations",
    "audit.emptyLoad": "Load a file to view the apply log",
    "audit.title": "Apply Log",
    "audit.warning": "Warnings",
    "audit.error": "Errors",
    "audit.none": "No log entries",
    "audit.periodSuffix": "period",
    "inspector.multiSelectMode": "Multi-select mode",
    "inspector.selectPeriodsPrompt": "Select periods",
    "inspector.nSelected": "{n} selected",
    "inspector.othersCount": "...and {n} more",
    "inspector.clearAll": "Clear all selections",
    "inspector.opDelete": "Delete",
    "inspector.opAdd": "Add",
    "inspector.opMove": "Move",
    "inspector.opSwap": "Swap",
    "inspector.opReason": "Reason",
    "inspector.opSubject": "Subject",
    "inspector.batchDeleteDesc": "Delete classes in the selected {n} periods",
    "inspector.batchAddDesc": "Batch-add to the selected {n} periods",
    "inspector.batchReasonDesc": "Batch-set a reason for the selected {n} periods",
    "inspector.batchSubjectDesc": "Batch-set the subject for the selected {n} periods",
    "inspector.classLabel": "Class",
    "inspector.homeroomHint": "(Homeroom: {c})",
    "inspector.notSet": "Not set",
    "inspector.selectClassPlaceholder": "Select a class...",
    "inspector.noneSelectable": "— None —",
    "inspector.notSpecified": "Not specified",
    "inspector.subjectNoneDelete": "No subject (delete)",
    "inspector.execDelete": "Delete {n} periods",
    "inspector.execAdd": "Add to {n} periods",
    "inspector.execReason": "Set reason for {n} periods",
    "inspector.execSubject": "Set subject for {n} periods",
    "inspector.selectedCell": "Selected period",
    "inspector.empty": "Free",
    "inspector.errNoSelection": "No periods selected",
    "inspector.errClassOrSubject": "Specify a class or subject",
    "inspector.errEnterReason": "Enter a reason",
    "inspector.errSelectMoveDate": "Select a destination date",
    "inspector.errSelectSwapDate": "Select a swap date",
    "inspector.okBatchDeleted": "Deleted {n} periods",
    "inspector.okBatchAdded": "Added “{label}” to {n} periods",
    "inspector.okBatchReason": "Set reason for {n} periods",
    "inspector.okBatchSubjectSet": "Set subject “{label}” for {n} periods",
    "inspector.okBatchSubjectDeleted": "Removed subject from {n} periods",
    "inspector.okDeleted": "Deleted: {d}",
    "inspector.okAdded": "Added: {label}",
    "inspector.okMoved": "Moved",
    "inspector.okSwapped": "Swapped",
    "inspector.okReasonSet": "Reason set",
    "inspector.okSubjectSet": "Subject set to “{label}”",
    "inspector.okSubjectDeleted": "Subject removed",
    "inspector.descDelete": "Delete the class at {d}",
    "inspector.descAdd": "Add a class at {d}",
    "inspector.descMove": "Move {from} to {to}",
    "inspector.descSwap": "Swap {a} and {b}",
    "inspector.descReason": "Set the reason for {d}",
    "inspector.descSubject": "Set the subject for {d}",
    "inspector.moveFrom": "From",
    "inspector.moveTo": "To",
    "inspector.moveOverwriteWarn": "The destination ({to}) already has {c}. It will be overwritten.",
    "inspector.none": "None",
    "inspector.noClass": "No class",
    "inspector.subjectPrefix": "Subject: {s}",
    "inspector.emptyPeriod": "Free period",
    "inspector.deleteTargetSuffix": "will be deleted",
    "inspector.selectClassBlankHint": "Select a class... (blank = none)",
    "inspector.specifyMoveDest": "Specify a destination",
    "inspector.specifySwapDest": "Specify a swap target",
    "inspector.swapTo": "Swap with",
    "inspector.moveDestOccupied": "⚠ The destination already has {c} (it will be overwritten)",
    "inspector.reasonOverwriteNote": "Set a reason (overwrites any existing reason)",
    "inspector.currentSubjectHint": "(current: {s})",
    "inspector.confirmDelete": "Confirm deletion",
    "inspector.confirmAdd": "Confirm addition",
    "inspector.confirmMove": "Confirm move",
    "inspector.confirmSwap": "Confirm swap",
    "inspector.confirmReason": "Confirm reason",
    "inspector.confirmSubject": "Confirm subject",
    "inspector.reasonField": "Reason",
    "inspector.subjectField": "Subject",
    "inspector.optional": "(optional)",
    "inspector.reasonPlaceholder": "Enter a reason...",
    "inspector.subjectNone": "No subject",
    "inspector.selectSubjectPlaceholder": "Select a subject...",
    "inspector.dateOf": "{label} date",
    "inspector.periodOf": "{label} period",
    "inspector.selectDatePlaceholder": "Select a date...",
    "inspector.setSubjectForCell": "Set the subject for this period",
    "dayEvents.cat.ceremony": "Ceremony",
    "dayEvents.cat.event": "Event",
    "dayEvents.cat.work": "Staff",
    "dayEvents.cat.student": "Class",
    "dayEvents.cat.holiday": "Holiday",
    "dayEvents.cat.other": "Other",
    "dayEvents.hint.ceremony": "Opening/entrance/graduation ceremonies",
    "dayEvents.hint.event": "Sports day, field trips, open class, assemblies",
    "dayEvents.hint.work": "Staff meetings, training, PTA",
    "dayEvents.hint.student": "Conferences, home visits, drills, health checks",
    "dayEvents.hint.holiday": "School closed days, public holidays",
    "dayEvents.hint.other": "Anything else",
    "dayEvents.contentPlaceholder": "Event details (e.g. Staff meeting)",
    "dayEvents.custom": "Custom:",
    "dayEvents.newTagPlaceholder": "New tag",
    "dayEvents.add": "Add",
    "dayEvents.save": "Save",
    "dayEvents.cancel": "Cancel",
    "dayEvents.addCustomCategory": "Add a custom category",
    "dayEvents.new": "New",
    "dayEvents.customTagLabel": "Custom tag “{c}”",
    "dayEvents.addCustomTagLink": "+ Add a custom tag",
    "dayEvents.notePlaceholder": "Note (optional)",
    "dayEvents.delete": "Delete",
    "dayEvents.editTitle": "Edit event — {date}",
    "dayEvents.addEventTitle": "Add event",
    "dayEvents.addEventHeader": "Add event — {date}",
    "dayEvents.eventsShort": "Events",
    "dayEvents.weekEvents": "This week's events",
    "dayEvents.countSuffix": "({n})",
    "dayEvents.weekdays": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "tp.notHeld": "Not held",
    "tp.noneBackToPlan": "— None (revert to plan)",
    "tp.planMark": "P",
    "tp.unitCellAuto": "Auto-planned (click to override)",
    "tp.unitCellClick": "Click to change unit",
    "tp.setUnit": "Set unit…",
    "tp.unitEditorHint": "Arrange units in order; set planned periods to auto-assign. Click ▶ to edit each period of a unit.",
    "tp.totalKoma": "Total {n} periods",
    "tp.komaUnit": "periods",
    "tp.filledCount": "({n} filled)",
    "tp.unitMasterHint": "Plan what to do in each period of this unit (master plan). Edits here appear as light text in the per-period list.",
    "tp.periodNo": "P{p}",
    "tp.periodContentPlaceholder": "Period {p} content (e.g. intro, practice, review)",
    "tp.newUnit": "New unit",
    "tp.addUnit": "Add unit",
    "tp.editUnitPeriods": "Edit each period of the unit",
    "tp.closeEdit": "Close",
    "tp.skipDesc": "Not held (excluded from planned period count)",
    "tp.notStarted": "Not started",
    "tp.done": "Done",
    "tp.todayMark": "▶ Today",
    "tp.nextMark": "→ Next",
    "tp.overflow": "Beyond schedule",
    "tp.overflowParen": " (beyond schedule)",
    "tp.behindShort": " ⚠ behind",
    "tp.advancedShort": " ⏩ ahead",
    "tp.contentPlaceholder": "Planned content",
    "tp.unitMasterPrefix": "Unit master: {c}",
    "tp.unitMasterClickOverride": "Unit master: {c} (click to override)",
    "tp.notesPlaceholder": "Notes (optional)",
    "tp.save": "Save",
    "tp.cancelEdit": "Cancel",
    "tp.clickToInput": "Click to enter…",
    "tp.classOnlyContent": "Content for this class only (optional)",
    "tp.classOnlyContentPh": "e.g. used for review / up to p.42",
    "tp.classNote": "Class-specific note",
    "tp.classNotePh": "e.g. ENT checkup, only half covered",
    "tp.contentOverrideMark": "Content overridden",
    "tp.noteExists": "Note ",
    "tp.behindLabel": "Behind ",
    "tp.advancedLabel": "Taught with previous period (ahead) ",
    "tp.cellClickHint": "{cls}: click to add note / progress mark",
    "tp.overflowTip": "{cls}: carry-over exceeded the loaded timetable range (advance the timetable to confirm the date)",
    "tp.behindToOverflow": "Behind on {from} → carried to {d} ",
    "tp.carriedOver": "Did not progress on {from}, so this row is carried over to {to}. Subsequent periods also shift back by one.",
    "tp.unitMgmt": "Unit management",
    "tp.unitMgmtEmptyHint": "(Add units to auto-assign them to periods)",
    "tp.allKoma": "{n} periods total",
    "tp.planAutoAssign": "{n} periods auto-assigned by plan",
    "tp.komaFilled": "{n} periods filled",
    "tp.komaNotHeld": "{n} periods not held",
    "tp.targetClasses": "Classes: {c}",
    "tp.opHint": "Click a unit cell → change unit / Click planned content → edit (light text = unit master) / Change row count via the unit panel period count / ",
    "tp.opHintClass": "Click a class's date cell → mark that class only as “behind” / add a note",
    "tp.colUnit": "Unit",
    "tp.colUnitInner": "In unit",
    "tp.colContent": "Planned content",
    "tp.noTimetableData": "No timetable data. Add periods in the weekly timetable to show them here automatically.",
    "tp.manualAddTitle": "Manually add a grade × subject",
    "tp.manualAddDesc": "Add a combination that doesn't exist in the timetable",
    "tp.gradeLabel": "Grade (e.g. Grade 5)",
    "tp.subjectLabel": "Subject (e.g. Science)",
    "tp.gradePh": "Grade 5",
    "tp.subjectPh": "Science",
    "tp.alreadyExists": "This combination already exists",
    "tp.cancel": "Cancel",
    "tp.add": "Add",
    "tp.classLabel": "Class",
    "tp.asOfLabel": "As of",
    "tp.todayBtn": "Today",
    "tp.viewLabel": "Show (multiple)",
    "tp.fieldUnit": "Unit",
    "tp.fieldContent": "Content",
    "tp.fieldDate": "Date",
    "tp.legendDone": "Done",
    "tp.legendToday": "Today",
    "tp.legendNext": "Next",
    "tp.legendNotYet": "Pending",
    "tp.legendBehind": "Behind",
    "tp.legendAhead": "Ahead",
    "tp.legendOverflow": "Beyond schedule",
    "tp.noClassSubjectData": "No subject data for this class",
    "tp.colSubject": "Subject",
    "tp.colProgress": "Progress",
    "tp.colCurrent": "Current",
    "tp.colNext": "Next",
    "tp.colNextDate": "Next date",
    "tp.colChart": "Progress chart",
    "tp.openSubjectPlan": "Open the teaching plan for this subject",
    "tp.unitNotSet": "(unit not set)",
    "tp.contentNotEntered": "(content not entered)",
    "tp.jumpHint": "Click a subject name to open its teaching plan (unit × period table).",
    "tp.gradeSubject": "Grade × Subject",
    "tp.notEntered": "Not entered",
    "tp.manualAdded": "Manually added",
    "tp.komaCountSuffix": "periods",
    "tp.hiddenN": "Hidden ({n})",
    "tp.allGradesHiddenN": "Hidden for all grades ({n})",
    "tp.allGrades": "All grades",
    "tp.allGradesParen": " (all grades)",
    "tp.tabHomeroom": "By class (homeroom)",
    "tp.tabSubject": "By subject (edit plan)",
    "tp.selectGradeSubject": "Select a grade × subject from the left",
    "tp.deleteThisPlan": "Delete this teaching plan's data",
    "tp.deleteConfirmTitle": "Delete teaching plan data?",
    "tp.deleteConfirmBody": "All entered lesson content and unit data will be deleted. This cannot be undone.",
    "tp.delete": "Delete",
    "tp.loadFilePrompt": "Please load a file",
    "tp.noSubjectData": "No subject data in the timetable",
    "tp.hideThisCombo": "Hide “{g} {s}” from the teaching plan list",
    "tp.showThisCombo": "Show “{g} {s}” again",
    "tp.hideAllGrades": "Hide “{s}” for all grades",
    "tp.showAllGrades": "Show “{s}” for all grades again",
    "tp.manualAddBtn": "Add manually",
    "tp.chartCellTitle": "P{n} {unit}",
    "tp.behindArrow": "↓ behind",
    "tp.carriedOverInfo": "Did not progress on {from}, so this row is carried over to {to}. Subsequent periods also shift back by one.",
    "tp.advancedInfo": "Taught together with the previous period on the same day (2 periods/day). This row onward shifts forward by one.",
    "tp.overflowInfo": "Accumulated carry-over exceeded the loaded timetable range. Advance the timetable to confirm the date (if there aren't enough spare periods, the plan needs adjusting).",
    "tp.behindCheckbox": "Behind",
    "tp.behindCheckboxHint": "The class was held but didn't progress as planned (→ subsequent periods shift back)",
    "tp.advancedCheckbox": "Ahead (advanced)",
    "tp.advancedCheckboxHint": "Taught together with the previous period on the same day (→ subsequent periods shift forward)",
    "tp.classContentEmptyHint": "If blank, the plan's “planned content” applies",
    "tp.clearAll": "Clear all",
    "tp.itemsCount": "{n}",
    "tp.completedFraction": "{a}/{b} done",
    "tp.behindBy": "-{n} behind",
    "tp.markLegend": "▶ = today  → = next  ✓ = done",
    "llm.templateAppend": "\n\n--- Fill in the JSON template below and return it ---\n",
    "llm.errPasteJson": "Please paste the JSON.",
    "llm.infoTimetableChecked": "Timetable JSON checked. Import it via the “Import” button (toolbar) using patch import.",
    "llm.errJsonFormat": "Invalid JSON format. Copy the LLM output as-is.",
    "llm.errPeriodTimesFormat": "Invalid period-times JSON format. Copy the LLM output as-is.",
    "llm.okPeriodTimesUpdated": "Period times updated.",
    "llm.errScheduleFormat": "Invalid annual-schedule JSON. Copy JSON containing an events or ops array.",
    "llm.errNothingToApply": "No events or operations to apply were found.",
    "llm.replacedWithEvents": "replaced with {n} events",
    "llm.removedOld": "removed {n} old",
    "llm.classChanges": "{n} class changes",
    "llm.eventsAppended": "appended {n} events",
    "llm.applied": "Applied",
    "llm.infoNothingToAdd": "There were no events to add",
    "llm.appendSummary": "appended {added}",
    "llm.skippedSuffix": " · skipped {n}",
    "llm.classChangesSuffix": " · {n} class changes",
    "llm.modeTimetable": "Timetable",
    "llm.descTimetable": "Read class placement from a weekly timetable image.",
    "llm.phTimetable": "Paste the JSON output by the LLM here...",
    "llm.noteTimetable": "※ Apply timetable JSON via patch import (toolbar “Import”).",
    "llm.modePeriodTimes": "Period times",
    "llm.descPeriodTimes": "Read each period's start/end time from a period-times image.",
    "llm.phPeriodTimes": "Paste the period-times JSON output by the LLM here...",
    "llm.notePeriodTimes": "Press “Apply” to update the period times.",
    "llm.modeSchedule": "Annual schedule",
    "llm.descSchedule": "Read events/closures from an annual schedule image and apply them.",
    "llm.phSchedule": "Paste the annual-schedule JSON output by the LLM here...",
    "llm.noteSchedule": "Press “Apply” to reflect events/closures in the timetable.",
    "llm.dialogTitle": "Read from an image with AI (LLM)",
    "llm.dialogDesc": "Use a generative AI (LLM — ChatGPT, Claude, Gemini, etc.) to auto-fill data from timetable, period-times, or annual-schedule images.",
    "llm.scopeLabel": "Import scope",
    "llm.scopeWithOps": "Include period cuts",
    "llm.scopeWithOpsDesc": "Also cut classes per rules",
    "llm.scopeEventsOnly": "Events only",
    "llm.scopeEventsOnlyDesc": "Never change class periods (safe)",
    "llm.modeLabel": "Import mode",
    "llm.modeAppend": "Append",
    "llm.modeAppendDesc": "Keep existing events and add (with duplicate check)",
    "llm.modeOverwrite": "Overwrite",
    "llm.modeOverwriteDesc": "Replace events within the imported date range",
    "llm.clearAllPrefix": "Clear ",
    "llm.clearAllWord": "all existing events",
    "llm.clearAllSuffix": " then fully replace (not limited to the date range)",
    "llm.scopeNoteProtected": "✓ Class periods are protected. Events only.",
    "llm.scopeNoteCut": "⚠ Rule-matching events will also delete class periods.",
    "llm.modeNoteAppend": " Append = add without removing existing.",
    "llm.modeNoteOverwriteAll": " Overwrite = delete all existing and fully replace.",
    "llm.modeNoteOverwriteRange": " Overwrite = replace only existing events in the imported date range (others kept).",
    "llm.stepRuleTitle": "Enter per-event class-cut rules (optional)",
    "llm.stepRuleDesc": "Tell the LLM closure rules per event. e.g. “Sports day: all periods cancelled”, “Field trip: no classes through period 4, periods 5–6 held”",
    "llm.stepRulePh": "e.g. Sports day: all periods cancelled. Field trip: no classes through period 4, periods 5–6 held. ...",
    "llm.stepPromptTitle": "Copy the LLM prompt",
    "llm.stepPromptDesc": "The JSON template is included. Just paste this one thing into the LLM.",
    "llm.copied": "Copied",
    "llm.copyPromptWithTemplate": "Copy prompt (with template)",
    "llm.advanced": "Advanced:",
    "llm.copyTemplateOnly": "Copy JSON template only",
    "llm.download": "Download",
    "llm.stepPasteTitle": "Paste into the AI with the image",
    "llm.stepPasteDesc": "Open ChatGPT, Claude, Gemini, etc., paste the copied “prompt (with template)” and the image, and send.",
    "llm.stepImportTitle": "Paste the JSON returned by the LLM and apply",
    "llm.appliedDone": "Applied.",
    "llm.dupTitle": "{n} events may be duplicates",
    "llm.dupDesc": "Similar events already exist on the same date. Only checked items will be added (duplicates skipped by default).",
    "llm.dupAddAll": "Add all",
    "llm.dupSkipAll": "Skip all",
    "llm.dupExisting": " ↔ existing “{title}”",
    "llm.dupConfirmAppend": "Confirm and append",
    "llm.cancel": "Cancel",
    "llm.dupAutoAdd": "{n} non-duplicate items will be added automatically.",
    "llm.apply": "Apply",
    "llm.hintLabel": "Tip:",
    "llm.hintBody": " Using image-capable models like GPT-4o or Claude 3.5 Sonnet improves accuracy. Always check the result before saving.",
    "llm.hintSchedule": " Annual schedules are complex; we recommend checking the result in the change history after applying.",
    "llm.close": "Close",
  },
} as const;

export type TranslationKey = keyof typeof translations.ja;

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

function readStoredLanguage(): Language {
  const stored = localStorage.getItem(STORAGE_KEY);
  return stored === "en" ? "en" : "ja";
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(readStoredLanguage);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage: setLanguageState,
    t: (key) => translations[language][key] ?? translations.ja[key],
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
